
create table if not exists solidos_control.source_recovery_current (
  source_slug text primary key references booked_solid.source_catalog(slug) on delete cascade,
  source_name text not null,
  enabled boolean not null,
  lifecycle_state text,
  rights_status text,
  sample_count integer not null default 0,
  lead_count integer not null default 0,
  qualified_count integer not null default 0,
  hot_high_count integer not null default 0,
  lead_rate numeric not null default 0,
  qualified_rate numeric not null default 0,
  hot_high_rate numeric not null default 0,
  median_company_to_lead_minutes numeric,
  commercial_yield_score numeric not null default 0,
  technical_reliability_score numeric not null default 0,
  source_value_score numeric not null default 0,
  recovery_mode text not null,
  portfolio_lane text not null,
  recommended_share_pct numeric not null default 0,
  reason text,
  computed_at timestamptz not null default now()
);
alter table solidos_control.source_recovery_current enable row level security;
revoke all on solidos_control.source_recovery_current from public,anon,authenticated;
grant select on solidos_control.source_recovery_current to service_role;

create table if not exists solidos_control.source_recovery_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'RUNNING' check(status in ('RUNNING','SUCCEEDED','FAILED')),
  sources_scored integer not null default 0,
  exploit_sources integer not null default 0,
  challenger_sources integer not null default 0,
  exploration_sources integer not null default 0,
  technical_recovery_sources integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  error text
);
alter table solidos_control.source_recovery_runs enable row level security;
revoke all on solidos_control.source_recovery_runs from public,anon,authenticated;
grant select on solidos_control.source_recovery_runs to service_role;

create index if not exists source_recovery_value_idx
  on solidos_control.source_recovery_current(source_value_score desc,portfolio_lane);

CREATE OR REPLACE FUNCTION solidos_control.refresh_source_recovery_v22()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_run bigint;
  v_total int;
  v_exploit int;
  v_challenger int;
  v_explore int;
  v_recovery int;
begin
  insert into solidos_control.source_recovery_runs(details)
  values(jsonb_build_object('policy_version',22))
  returning id into v_run;

  with lags as (
    select c.source_first_seen source_slug,
           percentile_cont(0.5) within group(
             order by extract(epoch from (l.created_at-c.created_at))/60.0
           ) median_lag
    from booked_solid.leads l
    join booked_solid.companies c on c.id=l.company_id
    where l.created_at>now()-interval '7 days'
      and c.source_first_seen is not null
    group by c.source_first_seen
  ),
  base as (
    select sc.slug source_slug,sc.name source_name,sc.enabled,sc.lifecycle_state,
           coalesce(sr.rights_status,'REVIEW_REQUIRED') rights_status,
           coalesce(y.sample_count,0) sample_count,
           coalesce(y.lead_count,0) lead_count,
           coalesce(y.qualified_count,0) qualified_count,
           coalesce(y.hot_high_count,0) hot_high_count,
           coalesce(y.lead_rate,0)::numeric lead_rate,
           coalesce(y.qualified_rate,0)::numeric qualified_rate,
           coalesce(y.hot_high_rate,0)::numeric hot_high_rate,
           lg.median_lag::numeric median_lag,
           coalesce(y.yield_score,0)::numeric yield_score,
           coalesce(sc.reliability_score,50)::numeric reliability_score,
           coalesce(sc.consecutive_errors,0) consecutive_errors,
           coalesce((sc.metadata->>'transient_failure')::boolean,false) transient_failure
    from booked_solid.source_catalog sc
    left join booked_solid.source_lead_yield_snapshot y on y.source_slug=sc.slug
    left join commercial_intel.source_rights sr on sr.source_slug=sc.slug
    left join lags lg on lg.source_slug=sc.slug
  ),
  scored as (
    select b.*,
      least(100,greatest(0,round(
        yield_score*0.55
        + least(25,lead_rate*40)
        + least(12,qualified_rate*45)
        + least(8,hot_high_rate*80)
        + case
            when median_lag is null then 0
            when median_lag<=10 then 8
            when median_lag<=30 then 5
            when median_lag<=60 then 3
            else 0
          end
      ,2))) commercial_score,
      least(100,greatest(0,round(
        reliability_score
        - least(30,consecutive_errors*2)
      ,2))) technical_score
    from base b
  ),
  classified as (
    select s.*,
      least(100,greatest(0,round(commercial_score*0.75+technical_score*0.25,2))) source_value_score,
      case
        when rights_status in ('BLOCKED','INTERNAL_ONLY') then 'blocked'
        when rights_status='REVIEW_REQUIRED' and commercial_score>=55
             and (not enabled or lifecycle_state in ('paused','degraded')) then 'technical_recovery_only'
        when rights_status='REVIEW_REQUIRED' then 'rights_review_only'
        when rights_status='ALLOWED' and commercial_score>=65 and technical_score>=65 then 'production_exploit'
        when rights_status='ALLOWED' and commercial_score>=35 and technical_score>=50 then 'production_challenger'
        when rights_status='ALLOWED' then 'production_exploration'
        else 'rights_review_only'
      end recovery_mode,
      case
        when rights_status='ALLOWED' and commercial_score>=65 and technical_score>=65 then 'champion'
        when rights_status='ALLOWED' and commercial_score>=35 and technical_score>=50 then 'challenger'
        when rights_status='ALLOWED' then 'exploration'
        when rights_status='REVIEW_REQUIRED' and commercial_score>=55
             and (not enabled or lifecycle_state in ('paused','degraded')) then 'technical_recovery'
        else 'blocked'
      end portfolio_lane,
      case
        when rights_status='ALLOWED' and commercial_score>=80 and technical_score>=75 then 30
        when rights_status='ALLOWED' and commercial_score>=65 and technical_score>=65 then 22
        when rights_status='ALLOWED' and commercial_score>=35 and technical_score>=50 then 10
        when rights_status='ALLOWED' then 3
        else 0
      end::numeric recommended_share_pct,
      case
        when rights_status='REVIEW_REQUIRED' and commercial_score>=55
          then 'Commercially strong but held behind source-rights gate; technical recovery/testing only.'
        when rights_status='ALLOWED' and commercial_score>=65 and technical_score>=65
          then 'High commercial yield with production-eligible rights and acceptable reliability.'
        when rights_status='ALLOWED' and sample_count>=20 and lead_count=0
          then 'Allowed source but mature zero-lead sample; exploration only.'
        when rights_status='BLOCKED' then 'Source rights blocked.'
        else null
      end reason
    from scored s
  )
  insert into solidos_control.source_recovery_current(
    source_slug,source_name,enabled,lifecycle_state,rights_status,sample_count,lead_count,
    qualified_count,hot_high_count,lead_rate,qualified_rate,hot_high_rate,
    median_company_to_lead_minutes,commercial_yield_score,technical_reliability_score,
    source_value_score,recovery_mode,portfolio_lane,recommended_share_pct,reason,computed_at
  )
  select source_slug,source_name,enabled,lifecycle_state,rights_status,sample_count,lead_count,
    qualified_count,hot_high_count,lead_rate,qualified_rate,hot_high_rate,
    round(median_lag,1),commercial_score,technical_score,source_value_score,
    recovery_mode,portfolio_lane,recommended_share_pct,reason,now()
  from classified
  on conflict(source_slug) do update set
    source_name=excluded.source_name,enabled=excluded.enabled,lifecycle_state=excluded.lifecycle_state,
    rights_status=excluded.rights_status,sample_count=excluded.sample_count,lead_count=excluded.lead_count,
    qualified_count=excluded.qualified_count,hot_high_count=excluded.hot_high_count,
    lead_rate=excluded.lead_rate,qualified_rate=excluded.qualified_rate,
    hot_high_rate=excluded.hot_high_rate,median_company_to_lead_minutes=excluded.median_company_to_lead_minutes,
    commercial_yield_score=excluded.commercial_yield_score,
    technical_reliability_score=excluded.technical_reliability_score,
    source_value_score=excluded.source_value_score,recovery_mode=excluded.recovery_mode,
    portfolio_lane=excluded.portfolio_lane,recommended_share_pct=excluded.recommended_share_pct,
    reason=excluded.reason,computed_at=excluded.computed_at;

  update booked_solid.source_catalog sc
  set metadata=jsonb_set(coalesce(sc.metadata,'{}'::jsonb),'{source_v22}',
    jsonb_build_object(
      'policy_version',22,
      'commercial_yield_score',r.commercial_yield_score,
      'technical_reliability_score',r.technical_reliability_score,
      'source_value_score',r.source_value_score,
      'recovery_mode',r.recovery_mode,
      'portfolio_lane',r.portfolio_lane,
      'recommended_share_pct',r.recommended_share_pct,
      'rights_status',r.rights_status,
      'median_company_to_lead_minutes',r.median_company_to_lead_minutes,
      'computed_at',r.computed_at
    ),true),
    updated_at=now()
  from solidos_control.source_recovery_current r
  where r.source_slug=sc.slug;

  select count(*),
    count(*) filter(where portfolio_lane='champion'),
    count(*) filter(where portfolio_lane='challenger'),
    count(*) filter(where portfolio_lane='exploration'),
    count(*) filter(where portfolio_lane='technical_recovery')
  into v_total,v_exploit,v_challenger,v_explore,v_recovery
  from solidos_control.source_recovery_current;

  update solidos_control.source_recovery_runs
  set finished_at=now(),status='SUCCEEDED',sources_scored=v_total,
      exploit_sources=v_exploit,challenger_sources=v_challenger,
      exploration_sources=v_explore,technical_recovery_sources=v_recovery,
      details=jsonb_build_object(
        'policy_version',22,
        'hard_rights_gate',true,
        'paid_search_changed',false,
        'tavily_enabled',false
      )
  where id=v_run;

  return jsonb_build_object(
    'ok',true,'run_id',v_run,'policy_version',22,'sources',v_total,
    'champions',v_exploit,'challengers',v_challenger,'exploration',v_explore,
    'technical_recovery',v_recovery
  );
exception when others then
  update solidos_control.source_recovery_runs
  set finished_at=now(),status='FAILED',error=left(sqlerrm,1000)
  where id=v_run;
  raise;
end
$function$
;

CREATE OR REPLACE FUNCTION solidos_control.source_recovery_snapshot()
 RETURNS jsonb
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
select jsonb_build_object(
  'at',now(),
  'latest_run',(select to_jsonb(r) from solidos_control.source_recovery_runs r order by id desc limit 1),
  'top_production',(
    select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)
    from (
      select source_slug,source_name,rights_status,commercial_yield_score,technical_reliability_score,
             source_value_score,portfolio_lane,recommended_share_pct,sample_count,lead_count,
             qualified_count,hot_high_count,median_company_to_lead_minutes
      from solidos_control.source_recovery_current
      where rights_status='ALLOWED'
      order by source_value_score desc
      limit 12
    ) x
  ),
  'technical_recovery',(
    select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)
    from (
      select source_slug,source_name,rights_status,commercial_yield_score,technical_reliability_score,
             source_value_score,recovery_mode,reason
      from solidos_control.source_recovery_current
      where recovery_mode='technical_recovery_only'
      order by commercial_yield_score desc
    ) x
  ),
  'safety',jsonb_build_object(
    'rights_gate',true,
    'review_required_in_exploit',false,
    'paid_search_enabled',false
  )
);
$function$
;

revoke all on function solidos_control.refresh_source_recovery_v22() from public,anon,authenticated;
grant execute on function solidos_control.refresh_source_recovery_v22() to service_role;
revoke all on function solidos_control.source_recovery_snapshot() from public,anon,authenticated;
grant execute on function solidos_control.source_recovery_snapshot() to service_role;

select cron.unschedule(jobid)
from cron.job where jobname='solidos-source-recovery-v22-10m';
select cron.schedule(
  'solidos-source-recovery-v22-10m',
  '8,18,28,38,48,58 * * * *',
  'select solidos_control.refresh_source_recovery_v22();'
);

select cron.unschedule(jobid)
from cron.job where jobname='solidos-osm-technical-recovery-probe';
select cron.schedule(
  'solidos-osm-technical-recovery-probe',
  '43 */2 * * *',
  $cron$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name='booked_solid_project_url') || '/functions/v1/booked-solid-worker',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'apikey',(select decrypted_secret from vault.decrypted_secrets where name='booked_solid_publishable_key')
    ),
    body := jsonb_build_object(
      'action','probe-source',
      'source_slug','openstreetmap_overpass',
      'source','solidos-osm-technical-recovery-probe'
    ),
    timeout_milliseconds := 30000
  ) as request_id;
  $cron$
);
