
alter table booked_solid.runtime_settings
  add column if not exists strategy_brain_enabled boolean not null default false,
  add column if not exists strategy_brain_canary_pct integer not null default 15,
  add column if not exists strategy_brain_policy_version integer not null default 2;

create table if not exists solidos_control.strategy_brain_baseline (
  id boolean primary key default true check(id=true),
  captured_at timestamptz not null default now(),
  metrics jsonb not null
);
alter table solidos_control.strategy_brain_baseline enable row level security;
revoke all on solidos_control.strategy_brain_baseline from public,anon,authenticated;
grant select on solidos_control.strategy_brain_baseline to service_role;

create table if not exists solidos_control.strategy_brain_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'RUNNING' check(status in ('RUNNING','SUCCEEDED','FAILED')),
  policy_version integer not null default 2,
  strategies_scored integer not null default 0,
  sources_scored integer not null default 0,
  markets_scored integer not null default 0,
  exploit_strategies integer not null default 0,
  deprioritized_strategies integer not null default 0,
  zero_yield_sources integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  error text
);
alter table solidos_control.strategy_brain_runs enable row level security;
revoke all on solidos_control.strategy_brain_runs from public,anon,authenticated;
grant select on solidos_control.strategy_brain_runs to service_role;

create table if not exists solidos_control.strategy_brain_strategy_current (
  strategy_id uuid primary key references booked_solid.search_strategies(id) on delete cascade,
  strategy_slug text not null,
  trade text,
  geography text,
  intent text,
  offer_hint text,
  attempts_14d integer not null default 0,
  leads_45d integer not null default 0,
  qualified_45d integer not null default 0,
  hot_high_45d integer not null default 0,
  act_now integer not null default 0,
  lead_rate numeric not null default 0,
  qualified_rate numeric not null default 0,
  hot_high_rate numeric not null default 0,
  act_now_rate numeric not null default 0,
  avg_opportunity numeric not null default 0,
  avg_trigger numeric not null default 0,
  avg_revenue_target numeric not null default 0,
  confidence numeric not null default 0,
  brain_score numeric not null default 0,
  decision text not null default 'test',
  negative_reason text,
  computed_at timestamptz not null default now()
);
alter table solidos_control.strategy_brain_strategy_current enable row level security;
revoke all on solidos_control.strategy_brain_strategy_current from public,anon,authenticated;
grant select on solidos_control.strategy_brain_strategy_current to service_role;
create index if not exists strategy_brain_strategy_score_idx on solidos_control.strategy_brain_strategy_current(brain_score desc,decision);

create table if not exists solidos_control.strategy_brain_source_current (
  source_slug text primary key references booked_solid.source_catalog(slug) on delete cascade,
  sample_count integer not null default 0,
  lead_count integer not null default 0,
  qualified_count integer not null default 0,
  hot_high_count integer not null default 0,
  lead_rate numeric not null default 0,
  qualified_rate numeric not null default 0,
  hot_high_rate numeric not null default 0,
  yield_score numeric not null default 0,
  quality_score numeric not null default 0,
  reliability_score numeric not null default 0,
  priority_yield_score numeric not null default 0,
  rights_status text,
  brain_score numeric not null default 0,
  lane text not null default 'testing',
  zero_yield_guard boolean not null default false,
  computed_at timestamptz not null default now()
);
alter table solidos_control.strategy_brain_source_current enable row level security;
revoke all on solidos_control.strategy_brain_source_current from public,anon,authenticated;
grant select on solidos_control.strategy_brain_source_current to service_role;
create index if not exists strategy_brain_source_score_idx on solidos_control.strategy_brain_source_current(brain_score desc,lane);

create table if not exists solidos_control.strategy_brain_market_current (
  market_id uuid primary key references booked_solid.market_catalog(id) on delete cascade,
  market_name text not null,
  discovered_count integer not null default 0,
  qualified_count integer not null default 0,
  qualified_rate numeric not null default 0,
  priority_yield_score numeric not null default 0,
  brain_score numeric not null default 0,
  decision text not null default 'test',
  computed_at timestamptz not null default now()
);
alter table solidos_control.strategy_brain_market_current enable row level security;
revoke all on solidos_control.strategy_brain_market_current from public,anon,authenticated;
grant select on solidos_control.strategy_brain_market_current to service_role;

create table if not exists solidos_control.source_candidate_registry (
  source_key text primary key,
  source_name text not null,
  source_class text not null,
  status text not null check(status in ('candidate','review_required','authorized_validation_only','approved_for_canary','rejected')),
  planner_enabled boolean not null default false,
  rights_review_required boolean not null default true,
  pii_allowed boolean not null default false,
  automated_messaging_allowed boolean not null default false,
  scraping_allowed boolean not null default false,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table solidos_control.source_candidate_registry enable row level security;
revoke all on solidos_control.source_candidate_registry from public,anon,authenticated;
grant select on solidos_control.source_candidate_registry to service_role;

insert into solidos_control.source_candidate_registry(source_key,source_name,source_class,status,planner_enabled,rights_review_required,pii_allowed,automated_messaging_allowed,scraping_allowed,notes,metadata)
values
('linkedin_authorized_validation','LinkedIn authorized validation','professional_network','authorized_validation_only',false,true,false,false,false,
 'No scraping, no automated messaging, no session/cookie automation. Use only through authorized access or manual/public validation after terms review.',
 jsonb_build_object('role','validation_only','production_discovery',false)),
('company_careers_pages','Company career pages','company_site_signal','review_required',false,true,false,false,false,
 'Candidate signal source for estimator/project-manager hiring and capacity signals. Must respect site terms and robots/rate limits.',
 jsonb_build_object('signals',jsonb_build_array('estimator_hiring','project_manager_hiring','capacity_growth'))),
('public_procurement_notices','Public procurement and bid notices','public_registry','review_required',false,true,false,false,false,
 'Candidate source for recent project/bid demand. Only official feeds with explicit reuse terms may graduate.',
 jsonb_build_object('signals',jsonb_build_array('bid_activity','project_demand','public_contracts'))),
('official_business_registries','Official business registries','public_registry','review_required',false,true,false,false,false,
 'Candidate validation/discovery source. Company-level fields only; no personal PII.',
 jsonb_build_object('signals',jsonb_build_array('active_business','new_entity','location_growth')))
on conflict(source_key) do update set
  source_name=excluded.source_name,source_class=excluded.source_class,status=excluded.status,
  planner_enabled=excluded.planner_enabled,rights_review_required=excluded.rights_review_required,
  pii_allowed=excluded.pii_allowed,automated_messaging_allowed=excluded.automated_messaging_allowed,
  scraping_allowed=excluded.scraping_allowed,notes=excluded.notes,metadata=excluded.metadata,updated_at=now();

insert into solidos_control.strategy_brain_baseline(id,metrics)
select true,jsonb_build_object(
  'captured_at',now(),
  'companies_total',(select count(*) from booked_solid.companies),
  'leads_total',(select count(*) from booked_solid.leads),
  'qualified_total',(select count(*) from booked_solid.leads where status in ('qualified','message_ready','queued','sent','replied','meeting','won')),
  'hot_total',(select count(*) from booked_solid.leads where upper(priority_band)='HOT'),
  'high_total',(select count(*) from booked_solid.leads where upper(priority_band)='HIGH'),
  'companies_60m',(select count(*) from booked_solid.companies where created_at>now()-interval '60 minutes'),
  'leads_60m',(select count(*) from booked_solid.leads where created_at>now()-interval '60 minutes'),
  'due_now',(select count(*) from booked_solid.work_queue where status='pending' and available_at<=now()),
  'running',(select count(*) from booked_solid.work_queue where status='running'),
  'stale_running',(select count(*) from booked_solid.work_queue where status='running' and locked_at<now()-interval '5 minutes')
)
on conflict(id) do nothing;

create or replace function solidos_control.refresh_strategy_brain_v2()
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_run bigint;
  v_strategies int;
  v_sources int;
  v_markets int;
  v_exploit int;
  v_deprioritized int;
  v_zero_sources int;
begin
  insert into solidos_control.strategy_brain_runs(policy_version)
  values(2) returning id into v_run;

  with attempts as (
    select payload->>'strategy_id' strategy_id_text,
           count(*) filter(where created_at>now()-interval '14 days')::int attempts_14d
    from booked_solid.work_queue
    where kind='discover' and payload ? 'strategy_id'
    group by payload->>'strategy_id'
  ),
  leads as (
    select l.strategy_id,
      count(*) filter(where l.created_at>now()-interval '45 days')::int leads_45d,
      count(*) filter(where l.created_at>now()-interval '45 days' and l.status in ('qualified','message_ready','queued','sent','replied','meeting','won'))::int qualified_45d,
      count(*) filter(where l.created_at>now()-interval '45 days' and upper(coalesce(l.priority_band,'')) in ('HOT','HIGH'))::int hot_high_45d,
      coalesce(avg(l.opportunity_score) filter(where l.created_at>now()-interval '45 days'),0)::numeric avg_opportunity,
      coalesce(avg(l.trigger_score) filter(where l.created_at>now()-interval '45 days'),0)::numeric avg_trigger
    from booked_solid.leads l
    where l.strategy_id is not null
    group by l.strategy_id
  ),
  revenue as (
    select l.strategy_id,
      count(*) filter(where r.readiness='ACT NOW')::int act_now,
      coalesce(avg(r.target_score),0)::numeric avg_target
    from solidos_control.revenue_intelligence_current r
    join booked_solid.leads l on l.id=r.lead_id
    where l.strategy_id is not null
    group by l.strategy_id
  ),
  base as (
    select s.id strategy_id,s.slug,s.trade,s.geography,s.intent,s.offer_hint,
      coalesce(a.attempts_14d,0) attempts_14d,
      coalesce(l.leads_45d,0) leads_45d,
      coalesce(l.qualified_45d,0) qualified_45d,
      coalesce(l.hot_high_45d,0) hot_high_45d,
      coalesce(r.act_now,0) act_now,
      least(1,coalesce(l.leads_45d,0)::numeric/greatest(coalesce(a.attempts_14d,0),1)) lead_rate,
      coalesce(l.qualified_45d,0)::numeric/greatest(coalesce(l.leads_45d,0),1) qualified_rate,
      coalesce(l.hot_high_45d,0)::numeric/greatest(coalesce(l.leads_45d,0),1) hot_high_rate,
      coalesce(r.act_now,0)::numeric/greatest(coalesce(l.leads_45d,0),1) act_now_rate,
      coalesce(l.avg_opportunity,0) avg_opportunity,
      coalesce(l.avg_trigger,0) avg_trigger,
      coalesce(r.avg_target,0) avg_target,
      least(1,(coalesce(a.attempts_14d,0)+coalesce(l.leads_45d,0)*2)::numeric/20) confidence,
      coalesce(s.performance_score,50)::numeric old_score
    from booked_solid.search_strategies s
    left join attempts a on a.strategy_id_text=s.id::text
    left join leads l on l.strategy_id=s.id
    left join revenue r on r.strategy_id=s.id
    where s.enabled
  ),
  scored as (
    select b.*,
      greatest(5,least(100,round(
        old_score*(1-0.65*confidence)
        +
        least(100,
          25
          + lead_rate*15
          + qualified_rate*25
          + hot_high_rate*30
          + act_now_rate*15
          + least(10,avg_target/10)
        )*(0.65*confidence)
        -
        case
          when attempts_14d>=12 and leads_45d=0 then 25
          when leads_45d>=5 and qualified_45d=0 then 12
          when leads_45d>=8 and avg_opportunity<35 then 8
          else 0
        end
      ,2))) brain_score,
      case
        when attempts_14d>=12 and leads_45d=0 then 'deprioritize'
        when leads_45d>=5 and qualified_45d=0 and avg_opportunity<45 then 'deprioritize'
        when hot_high_45d>=1 then 'exploit'
        when leads_45d>=4 and qualified_rate>=0.30 then 'exploit'
        else 'test'
      end decision,
      case
        when attempts_14d>=12 and leads_45d=0 then '12+ discovery attempts with zero downstream leads'
        when leads_45d>=5 and qualified_45d=0 and avg_opportunity<45 then '5+ leads but zero qualified and weak opportunity quality'
        when leads_45d>=8 and avg_opportunity<35 then 'low opportunity quality at meaningful sample'
        else null
      end negative_reason
    from base b
  )
  insert into solidos_control.strategy_brain_strategy_current(
    strategy_id,strategy_slug,trade,geography,intent,offer_hint,attempts_14d,leads_45d,qualified_45d,
    hot_high_45d,act_now,lead_rate,qualified_rate,hot_high_rate,act_now_rate,avg_opportunity,avg_trigger,
    avg_revenue_target,confidence,brain_score,decision,negative_reason,computed_at
  )
  select strategy_id,slug,trade,geography,intent,offer_hint,attempts_14d,leads_45d,qualified_45d,
    hot_high_45d,act_now,round(lead_rate,4),round(qualified_rate,4),round(hot_high_rate,4),round(act_now_rate,4),
    round(avg_opportunity,2),round(avg_trigger,2),round(avg_target,2),round(confidence,4),brain_score,decision,negative_reason,now()
  from scored
  on conflict(strategy_id) do update set
    strategy_slug=excluded.strategy_slug,trade=excluded.trade,geography=excluded.geography,intent=excluded.intent,
    offer_hint=excluded.offer_hint,attempts_14d=excluded.attempts_14d,leads_45d=excluded.leads_45d,
    qualified_45d=excluded.qualified_45d,hot_high_45d=excluded.hot_high_45d,act_now=excluded.act_now,
    lead_rate=excluded.lead_rate,qualified_rate=excluded.qualified_rate,hot_high_rate=excluded.hot_high_rate,
    act_now_rate=excluded.act_now_rate,avg_opportunity=excluded.avg_opportunity,avg_trigger=excluded.avg_trigger,
    avg_revenue_target=excluded.avg_revenue_target,confidence=excluded.confidence,brain_score=excluded.brain_score,
    decision=excluded.decision,negative_reason=excluded.negative_reason,computed_at=excluded.computed_at;

  delete from solidos_control.strategy_brain_strategy_current b
  where not exists(select 1 from booked_solid.search_strategies s where s.id=b.strategy_id and s.enabled);

  with src as (
    select sc.slug,
      coalesce(y.sample_count,0) sample_count,coalesce(y.lead_count,0) lead_count,
      coalesce(y.qualified_count,0) qualified_count,coalesce(y.hot_high_count,0) hot_high_count,
      coalesce(y.lead_rate,0) lead_rate,coalesce(y.qualified_rate,0) qualified_rate,
      coalesce(y.hot_high_rate,0) hot_high_rate,coalesce(y.yield_score,0) yield_score,
      coalesce(sc.quality_score,50) quality_score,coalesce(sc.reliability_score,50) reliability_score,
      coalesce((sc.metadata->>'priority_yield_score')::numeric,25) priority_yield_score,
      sr.rights_status,sc.lifecycle_state,sc.enabled
    from booked_solid.source_catalog sc
    left join booked_solid.source_lead_yield_snapshot y on y.source_slug=sc.slug
    left join commercial_intel.source_rights sr on sr.source_slug=sc.slug
    where sc.enabled
  ),
  scored as (
    select s.*,
      (sample_count>=20 and lead_count=0) zero_guard,
      greatest(0,least(100,round(
        yield_score*0.55 + quality_score*0.20 + reliability_score*0.15 + priority_yield_score*0.10
        - case when sample_count>=40 and lead_count=0 then 25 when sample_count>=20 and lead_count=0 then 15 else 0 end
        + case when hot_high_count>0 then 8 else 0 end
      ,2))) brain_score,
      case
        when rights_status='BLOCKED' or lifecycle_state in ('degraded','paused','retired') then 'blocked'
        when sample_count>=20 and lead_count=0 then 'exploration'
        when yield_score>=40 and (qualified_count>0 or hot_high_count>0) then 'proven'
        when lead_count>0 or sample_count<10 then 'testing'
        else 'exploration'
      end lane
    from src s
  )
  insert into solidos_control.strategy_brain_source_current(
    source_slug,sample_count,lead_count,qualified_count,hot_high_count,lead_rate,qualified_rate,hot_high_rate,
    yield_score,quality_score,reliability_score,priority_yield_score,rights_status,brain_score,lane,zero_yield_guard,computed_at
  )
  select slug,sample_count,lead_count,qualified_count,hot_high_count,lead_rate,qualified_rate,hot_high_rate,
    yield_score,quality_score,reliability_score,priority_yield_score,rights_status,brain_score,lane,zero_guard,now()
  from scored
  on conflict(source_slug) do update set
    sample_count=excluded.sample_count,lead_count=excluded.lead_count,qualified_count=excluded.qualified_count,
    hot_high_count=excluded.hot_high_count,lead_rate=excluded.lead_rate,qualified_rate=excluded.qualified_rate,
    hot_high_rate=excluded.hot_high_rate,yield_score=excluded.yield_score,quality_score=excluded.quality_score,
    reliability_score=excluded.reliability_score,priority_yield_score=excluded.priority_yield_score,
    rights_status=excluded.rights_status,brain_score=excluded.brain_score,lane=excluded.lane,
    zero_yield_guard=excluded.zero_yield_guard,computed_at=excluded.computed_at;

  delete from solidos_control.strategy_brain_source_current b
  where not exists(select 1 from booked_solid.source_catalog s where s.slug=b.source_slug and s.enabled);

  insert into solidos_control.strategy_brain_market_current(
    market_id,market_name,discovered_count,qualified_count,qualified_rate,priority_yield_score,brain_score,decision,computed_at
  )
  select m.id,m.display_name,coalesce(m.discovered_count,0),coalesce(m.qualified_count,0),
    round(coalesce(m.qualified_count,0)::numeric/greatest(coalesce(m.discovered_count,0),1),4),
    coalesce((m.metadata->>'priority_yield_score')::numeric,25),
    greatest(5,least(100,round(
      coalesce(m.quality_score,50)*0.35
      + coalesce((m.metadata->>'priority_yield_score')::numeric,25)*0.35
      + least(100,coalesce(m.qualified_count,0)::numeric/greatest(coalesce(m.discovered_count,0),1)*100)*0.30
      - case when coalesce(m.discovered_count,0)>=30 and coalesce(m.qualified_count,0)=0 then 15 else 0 end
    ,2))),
    case
      when coalesce(m.discovered_count,0)>=30 and coalesce(m.qualified_count,0)=0 then 'deprioritize'
      when coalesce(m.qualified_count,0)>=2 or coalesce((m.metadata->>'priority_yield_score')::numeric,25)>=35 then 'exploit'
      else 'test'
    end,
    now()
  from booked_solid.market_catalog m
  where m.lifecycle_state in ('testing','active')
  on conflict(market_id) do update set
    market_name=excluded.market_name,discovered_count=excluded.discovered_count,qualified_count=excluded.qualified_count,
    qualified_rate=excluded.qualified_rate,priority_yield_score=excluded.priority_yield_score,
    brain_score=excluded.brain_score,decision=excluded.decision,computed_at=excluded.computed_at;

  update booked_solid.search_strategies s
  set metadata=jsonb_set(coalesce(s.metadata,'{}'::jsonb),'{brain_v2}',
    jsonb_build_object(
      'policy_version',2,'score',b.brain_score,'decision',b.decision,'confidence',b.confidence,
      'attempts_14d',b.attempts_14d,'leads_45d',b.leads_45d,'qualified_45d',b.qualified_45d,
      'hot_high_45d',b.hot_high_45d,'act_now',b.act_now,'lead_rate',b.lead_rate,
      'qualified_rate',b.qualified_rate,'hot_high_rate',b.hot_high_rate,
      'avg_revenue_target',b.avg_revenue_target,'negative_reason',b.negative_reason,'computed_at',b.computed_at
    ),true)
  from solidos_control.strategy_brain_strategy_current b
  where b.strategy_id=s.id;

  update booked_solid.source_catalog s
  set metadata=jsonb_set(coalesce(s.metadata,'{}'::jsonb),'{brain_v2}',
    jsonb_build_object(
      'policy_version',2,'score',b.brain_score,'lane',b.lane,'sample',b.sample_count,
      'leads',b.lead_count,'qualified',b.qualified_count,'hot_high',b.hot_high_count,
      'zero_yield_guard',b.zero_yield_guard,'rights_status',b.rights_status,'computed_at',b.computed_at
    ),true)
  from solidos_control.strategy_brain_source_current b
  where b.source_slug=s.slug;

  update booked_solid.market_catalog m
  set metadata=jsonb_set(coalesce(m.metadata,'{}'::jsonb),'{brain_v2}',
    jsonb_build_object(
      'policy_version',2,'score',b.brain_score,'decision',b.decision,
      'discovered',b.discovered_count,'qualified',b.qualified_count,'qualified_rate',b.qualified_rate,
      'computed_at',b.computed_at
    ),true)
  from solidos_control.strategy_brain_market_current b
  where b.market_id=m.id;

  select count(*),count(*) filter(where decision='exploit'),count(*) filter(where decision='deprioritize')
  into v_strategies,v_exploit,v_deprioritized
  from solidos_control.strategy_brain_strategy_current;

  select count(*),count(*) filter(where zero_yield_guard)
  into v_sources,v_zero_sources
  from solidos_control.strategy_brain_source_current;

  select count(*) into v_markets from solidos_control.strategy_brain_market_current;

  update solidos_control.strategy_brain_runs
  set finished_at=now(),status='SUCCEEDED',strategies_scored=v_strategies,sources_scored=v_sources,
      markets_scored=v_markets,exploit_strategies=v_exploit,deprioritized_strategies=v_deprioritized,
      zero_yield_sources=v_zero_sources,
      details=jsonb_build_object(
        'mode',(select case when strategy_brain_enabled then 'enabled' else 'shadow' end from booked_solid.runtime_settings where id=true),
        'canary_pct',(select strategy_brain_canary_pct from booked_solid.runtime_settings where id=true),
        'safety',jsonb_build_object('email',false,'sms',false,'outreach',false,'pii_export',false)
      )
  where id=v_run;

  return jsonb_build_object(
    'ok',true,'run_id',v_run,'policy_version',2,'strategies_scored',v_strategies,
    'exploit_strategies',v_exploit,'deprioritized_strategies',v_deprioritized,
    'sources_scored',v_sources,'zero_yield_sources',v_zero_sources,'markets_scored',v_markets,
    'brain_enabled',(select strategy_brain_enabled from booked_solid.runtime_settings where id=true),
    'canary_pct',(select strategy_brain_canary_pct from booked_solid.runtime_settings where id=true)
  );
exception when others then
  update solidos_control.strategy_brain_runs set finished_at=now(),status='FAILED',error=left(sqlerrm,1000) where id=v_run;
  raise;
end
$function$;

revoke all on function solidos_control.refresh_strategy_brain_v2() from public,anon,authenticated;
grant execute on function solidos_control.refresh_strategy_brain_v2() to service_role;

select cron.unschedule(jobid) from cron.job where jobname='solidos-strategy-brain-v2-10m';
select cron.schedule('solidos-strategy-brain-v2-10m','9,19,29,39,49,59 * * * *','select solidos_control.refresh_strategy_brain_v2();');
