
create table if not exists solidos_control.pipeline_milestones (
  id bigint generated by default as identity primary key,
  company_id uuid references booked_solid.companies(id) on delete cascade,
  lead_id uuid references booked_solid.leads(id) on delete cascade,
  stage text not null check(stage in ('discovery','resolved','lead','qualified','contact')),
  event_at timestamptz not null,
  exact boolean not null default true,
  source text not null default 'trigger',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pipeline_milestones_company_stage_time_idx
  on solidos_control.pipeline_milestones(company_id,stage,event_at);
create index if not exists pipeline_milestones_lead_stage_time_idx
  on solidos_control.pipeline_milestones(lead_id,stage,event_at)
  where lead_id is not null;

alter table solidos_control.pipeline_milestones enable row level security;

create unique index if not exists pipeline_milestones_exact_once_idx
on solidos_control.pipeline_milestones(
  company_id,
  coalesce(lead_id,'00000000-0000-0000-0000-000000000000'::uuid),
  stage,
  source
)
where exact=true and source='trigger';

create or replace function solidos_control.capture_company_milestone()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  if tg_op='INSERT' then
    insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
    values(new.id,'discovery',coalesce(new.created_at,now()),true,'trigger')
    on conflict do nothing;

    if new.website_url is not null or new.canonical_domain is not null then
      insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
      values(new.id,'resolved',coalesce(new.updated_at,now()),true,'trigger')
      on conflict do nothing;
    end if;
  elsif tg_op='UPDATE' then
    if (old.website_url is null and new.website_url is not null)
       or (old.canonical_domain is null and new.canonical_domain is not null) then
      insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
      values(new.id,'resolved',now(),true,'trigger')
      on conflict do nothing;
    end if;
  end if;
  return new;
end
$function$;

create or replace function solidos_control.capture_lead_milestone()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_qualified boolean;
  v_old_qualified boolean:=false;
begin
  v_qualified:=new.status in ('qualified','message_ready','queued','sent','replied','meeting','won');

  if tg_op='INSERT' then
    insert into solidos_control.pipeline_milestones(company_id,lead_id,stage,event_at,exact,source)
    values(new.company_id,new.id,'lead',coalesce(new.created_at,now()),true,'trigger')
    on conflict do nothing;

    if v_qualified then
      insert into solidos_control.pipeline_milestones(company_id,lead_id,stage,event_at,exact,source)
      values(new.company_id,new.id,'qualified',now(),true,'trigger')
      on conflict do nothing;
    end if;
  else
    v_old_qualified:=old.status in ('qualified','message_ready','queued','sent','replied','meeting','won');
    if v_qualified and not v_old_qualified then
      insert into solidos_control.pipeline_milestones(company_id,lead_id,stage,event_at,exact,source)
      values(new.company_id,new.id,'qualified',now(),true,'trigger')
      on conflict do nothing;
    end if;
  end if;
  return new;
end
$function$;

create or replace function solidos_control.capture_contact_milestone()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
begin
  insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
  values(new.company_id,'contact',coalesce(new.created_at,now()),true,'trigger')
  on conflict do nothing;
  return new;
end
$function$;

drop trigger if exists solidos_pipeline_company_milestone on booked_solid.companies;
create trigger solidos_pipeline_company_milestone
after insert or update of website_url,canonical_domain on booked_solid.companies
for each row execute function solidos_control.capture_company_milestone();

drop trigger if exists solidos_pipeline_lead_milestone on booked_solid.leads;
create trigger solidos_pipeline_lead_milestone
after insert or update of status on booked_solid.leads
for each row execute function solidos_control.capture_lead_milestone();

drop trigger if exists solidos_pipeline_contact_milestone on booked_solid.contacts;
create trigger solidos_pipeline_contact_milestone
after insert on booked_solid.contacts
for each row execute function solidos_control.capture_contact_milestone();

-- Historical backfill is deliberately marked exact=false.
insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
select c.id,'discovery',c.created_at,false,'backfill'
from booked_solid.companies c
where not exists(
  select 1 from solidos_control.pipeline_milestones m
  where m.company_id=c.id and m.stage='discovery' and m.source='backfill'
);

insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
select c.id,'resolved',coalesce(c.last_researched_at,c.updated_at),false,'backfill'
from booked_solid.companies c
where (c.website_url is not null or c.canonical_domain is not null)
and not exists(
  select 1 from solidos_control.pipeline_milestones m
  where m.company_id=c.id and m.stage='resolved' and m.source='backfill'
);

insert into solidos_control.pipeline_milestones(company_id,lead_id,stage,event_at,exact,source)
select l.company_id,l.id,'lead',l.created_at,false,'backfill'
from booked_solid.leads l
where not exists(
  select 1 from solidos_control.pipeline_milestones m
  where m.lead_id=l.id and m.stage='lead' and m.source='backfill'
);

insert into solidos_control.pipeline_milestones(company_id,lead_id,stage,event_at,exact,source)
select l.company_id,l.id,'qualified',l.updated_at,false,'backfill'
from booked_solid.leads l
where l.status in ('qualified','message_ready','queued','sent','replied','meeting','won')
and not exists(
  select 1 from solidos_control.pipeline_milestones m
  where m.lead_id=l.id and m.stage='qualified' and m.source='backfill'
);

insert into solidos_control.pipeline_milestones(company_id,stage,event_at,exact,source)
select ct.company_id,'contact',min(ct.created_at),false,'backfill'
from booked_solid.contacts ct
group by ct.company_id
having not exists(
  select 1 from solidos_control.pipeline_milestones m
  where m.company_id=ct.company_id and m.stage='contact' and m.source='backfill'
);

create or replace function solidos_control.pipeline_end_to_end_v2()
returns jsonb
language sql
security definer
set search_path=''
as $function$
with exact_pairs as (
  select
    d.company_id,
    d.event_at discovery_at,
    min(l.event_at) filter(where l.stage='lead') lead_at,
    min(q.event_at) filter(where q.stage='qualified') qualified_at,
    min(c.event_at) filter(where c.stage='contact') contact_at
  from solidos_control.pipeline_milestones d
  left join solidos_control.pipeline_milestones l
    on l.company_id=d.company_id and l.exact=true and l.stage='lead' and l.event_at>=d.event_at
  left join solidos_control.pipeline_milestones q
    on q.company_id=d.company_id and q.exact=true and q.stage='qualified' and q.event_at>=d.event_at
  left join solidos_control.pipeline_milestones c
    on c.company_id=d.company_id and c.exact=true and c.stage='contact' and c.event_at>=d.event_at
  where d.stage='discovery' and d.exact=true
  group by d.company_id,d.event_at
),
qualified_to_sheet as (
  select q.id,q.event_at,
    (select min(s.finished_at)
     from solidos_control.sheet_sync_requests s
     where s.sync_scope='CORE_CRM'
       and s.status='SUCCEEDED'
       and s.finished_at>=q.event_at
       and (
         s.reason='hourly_full_refresh'
         or coalesce((s.payload->>'force_full')::boolean,false)
         or coalesce((s.payload->>'changed_leads')::boolean,false)
       )
    ) sheet_at
  from solidos_control.pipeline_milestones q
  where q.stage='qualified' and q.exact=true
)
select jsonb_build_object(
  'at',now(),
  'exact_since',(select min(created_at) from solidos_control.pipeline_milestones where exact=true),
  'exact_discovery_samples',(select count(*) from exact_pairs),
  'exact_discovery_to_lead_samples',(select count(*) from exact_pairs where lead_at is not null),
  'exact_discovery_to_qualified_samples',(select count(*) from exact_pairs where qualified_at is not null),
  'exact_discovery_to_contact_samples',(select count(*) from exact_pairs where contact_at is not null),
  'discovery_to_lead_p50_seconds_exact',(
    select round(percentile_cont(.5) within group(order by extract(epoch from(lead_at-discovery_at)))::numeric,1)
    from exact_pairs where lead_at is not null
  ),
  'discovery_to_qualified_p50_seconds_exact',(
    select round(percentile_cont(.5) within group(order by extract(epoch from(qualified_at-discovery_at)))::numeric,1)
    from exact_pairs where qualified_at is not null
  ),
  'discovery_to_contact_p50_seconds_exact',(
    select round(percentile_cont(.5) within group(order by extract(epoch from(contact_at-discovery_at)))::numeric,1)
    from exact_pairs where contact_at is not null
  ),
  'qualified_to_sheet_samples_exact',(select count(*) from qualified_to_sheet where sheet_at is not null),
  'qualified_to_sheet_p50_seconds_exact',(
    select round(percentile_cont(.5) within group(order by extract(epoch from(sheet_at-event_at)))::numeric,1)
    from qualified_to_sheet where sheet_at is not null
  ),
  'historical_backfill_samples',(select count(*) from solidos_control.pipeline_milestones where exact=false),
  'note','exact metrics begin at milestone instrumentation deployment; historical backfill is retained separately and never mixed into exact latency percentiles'
);
$function$;

revoke all on function solidos_control.pipeline_end_to_end_v2() from public,anon,authenticated;
grant execute on function solidos_control.pipeline_end_to_end_v2() to service_role;
