create table if not exists solidos_control.dead_letter (
  work_queue_id uuid primary key references booked_solid.work_queue(id) on delete cascade,
  kind text not null,payload jsonb not null default '{}'::jsonb,attempts integer not null,last_error text,
  first_seen_at timestamptz,failed_at timestamptz not null,source_slug text,failure_class text,
  recovery_status text not null default 'UNRESOLVED'
    check(recovery_status in ('UNRESOLVED','RETRY_SCHEDULED','RECOVERED','IGNORED')),
  metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists dead_letter_status_idx on solidos_control.dead_letter(recovery_status,failed_at desc);

insert into solidos_control.dead_letter(
 work_queue_id,kind,payload,attempts,last_error,first_seen_at,failed_at,source_slug,failure_class
)
select q.id,q.kind,coalesce(q.payload,'{}'::jsonb),q.attempts,q.last_error,q.created_at,q.updated_at,
 q.payload->>'source_slug',
 case when coalesce(q.last_error,'') ~* 'overpass.*(504|406|http_0)|overpass_transient' then 'overpass_transient'
      when coalesce(q.last_error,'') ~* 'timeout' then 'network_timeout'
      when coalesce(q.last_error,'') ~* '429|rate' then 'rate_limit'
      else 'unknown' end
from booked_solid.work_queue q where q.status='failed'
on conflict(work_queue_id) do nothing;

create or replace view solidos_control.source_health
with (security_invoker=true)
as
with r as (
 select source_id,
  count(*) filter(where started_at>now()-interval '24 hours')::int runs_24h,
  count(*) filter(where started_at>now()-interval '24 hours' and status='succeeded')::int success_24h,
  count(*) filter(where started_at>now()-interval '24 hours' and status<>'succeeded')::int failed_24h,
  coalesce(sum(discovered_count) filter(where started_at>now()-interval '24 hours'),0)::int discovered_24h,
  coalesce(sum(qualified_count) filter(where started_at>now()-interval '24 hours'),0)::int qualified_24h,
  round(avg(extract(epoch from(finished_at-started_at))) filter(
    where started_at>now()-interval '24 hours' and finished_at is not null)::numeric,3) avg_run_seconds_24h,
  max(finished_at) filter(where status='succeeded') last_run_success_at,
  max(finished_at) filter(where status<>'succeeded') last_run_failure_at
 from booked_solid.runs group by source_id
)
select s.id source_id,s.slug,s.name,s.enabled,s.lifecycle_state,s.reliability_score,s.quality_score,
 s.exploration_weight,s.consecutive_errors,coalesce(r.runs_24h,0) runs_24h,
 coalesce(r.success_24h,0) success_24h,coalesce(r.failed_24h,0) failed_24h,
 case when coalesce(r.runs_24h,0)>0 then round((100.0*r.success_24h/r.runs_24h)::numeric,2) end success_rate_24h,
 coalesce(r.discovered_24h,0) discovered_24h,coalesce(r.qualified_24h,0) qualified_24h,
 r.avg_run_seconds_24h,r.last_run_success_at,r.last_run_failure_at,
 s.metadata->>'last_error_class' last_error_class,
 nullif(s.metadata->>'cooldown_until','')::timestamptz cooldown_until,
 case when not s.enabled then 'DISABLED'
      when nullif(s.metadata->>'cooldown_until','') is not null
        and (s.metadata->>'cooldown_until')::timestamptz>now() then 'COOLING'
      when s.consecutive_errors>=4 then 'DEGRADED'
      when coalesce(r.runs_24h,0)>=3 and (100.0*r.success_24h/r.runs_24h)<60 then 'DEGRADED'
      else 'HEALTHY' end health_state
from booked_solid.source_catalog s left join r on r.source_id=s.id;

create table if not exists solidos_control.sheet_sync_requests (
  id bigint generated by default as identity primary key,
  sync_scope text not null check(sync_scope in ('CORE_CRM','COMMERCIAL_PRODUCTS')),
  target_key text,reason text not null,
  status text not null default 'PENDING'
    check(status in ('PENDING','RUNNING','SUCCEEDED','FAILED','BLOCKED_NOT_CONFIGURED')),
  requested_at timestamptz not null default now(),
  debounce_until timestamptz not null default now()+interval '90 seconds',
  started_at timestamptz,finished_at timestamptz,attempts integer not null default 0,last_error text,
  payload jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now()
);
create index if not exists sheet_sync_requests_pick_idx
 on solidos_control.sheet_sync_requests(status,debounce_until,requested_at);
create unique index if not exists sheet_sync_requests_one_pending_scope_idx
 on solidos_control.sheet_sync_requests(sync_scope) where status='PENDING';

create or replace function solidos_control.request_sheet_sync(
 p_scope text,p_reason text,p_payload jsonb default '{}'::jsonb
) returns void
language plpgsql security invoker set search_path=''
as $function$
begin
 if p_scope not in ('CORE_CRM','COMMERCIAL_PRODUCTS') then raise exception 'invalid sync scope'; end if;
 insert into solidos_control.sheet_sync_requests(sync_scope,reason,payload)
 values(p_scope,coalesce(nullif(p_reason,''),'data_changed'),coalesce(p_payload,'{}'::jsonb))
 on conflict(sync_scope) where status='PENDING'
 do update set reason=excluded.reason,
  payload=solidos_control.sheet_sync_requests.payload||excluded.payload,
  debounce_until=greatest(solidos_control.sheet_sync_requests.debounce_until,now()+interval '90 seconds'),
  updated_at=now();
end
$function$;

create or replace function commercial_intel.process_dirty_companies(p_limit integer default 50)
returns jsonb language plpgsql security invoker set search_path=''
as $function$
declare r record; v_ok integer:=0; v_failed integer:=0; v_limit integer;
begin
 v_limit:=least(greatest(coalesce(p_limit,50),1),500);
 for r in select company_id from solidos_control.dirty_companies
   order by priority desc,last_dirty_at,company_id for update skip locked limit v_limit
 loop
  begin
   update solidos_control.dirty_companies set locked_at=now(),attempts=attempts+1,updated_at=now()
    where company_id=r.company_id;
   perform commercial_intel.refresh_company_incremental(r.company_id);
   delete from solidos_control.dirty_companies where company_id=r.company_id;
   v_ok:=v_ok+1;
  exception when others then
   update solidos_control.dirty_companies set locked_at=null,last_error=left(sqlerrm,500),updated_at=now()
    where company_id=r.company_id;
   v_failed:=v_failed+1;
  end;
 end loop;
 if v_ok>0 then
  perform solidos_control.request_sheet_sync('COMMERCIAL_PRODUCTS','incremental_intel_update',
   jsonb_build_object('companies_processed',v_ok,'requested_at',now()));
 end if;
 return jsonb_build_object('processed',v_ok,'failed',v_failed,
  'remaining',(select count(*) from solidos_control.dirty_companies),'at',now());
end
$function$;

create or replace function solidos_control.core_change_dirty_trigger()
returns trigger language plpgsql security invoker set search_path=''
as $function$
declare v_company uuid;
begin
 if tg_table_name='companies' then v_company:=new.id; else v_company:=new.company_id; end if;
 perform solidos_control.mark_company_dirty(v_company,tg_table_name||':'||lower(tg_op),
   case when tg_table_name in ('leads','evidence') then 80 else 60 end);
 perform solidos_control.request_sheet_sync('CORE_CRM',tg_table_name||':'||lower(tg_op),
   jsonb_build_object('company_id',v_company,'table',tg_table_name));
 return new;
end
$function$;


create or replace function solidos_control.system_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path=''
as $function$
select jsonb_build_object(
  'system','SolidOS','snapshot_at',now(),
  'mode',(select mode from solidos_control.settings where id=true),
  'core',jsonb_build_object(
    'companies',(select count(*) from booked_solid.companies),
    'leads',(select count(*) from booked_solid.leads),
    'qualified',(select count(*) from booked_solid.leads where lower(status)='qualified'),
    'candidates',(select count(*) from booked_solid.leads where lower(status)='candidate'),
    'due_now',(select count(*) from booked_solid.work_queue where status='pending' and available_at<=now()),
    'scheduled_future',(select count(*) from booked_solid.work_queue where status='pending' and available_at>now()),
    'running',(select count(*) from booked_solid.work_queue where status='running'),
    'failed_terminal',(select count(*) from booked_solid.work_queue where status='failed'),
    'dead_letter_unresolved',(select count(*) from solidos_control.dead_letter where recovery_status='UNRESOLVED')
  ),
  'intel',jsonb_build_object(
    'dirty_backlog',(select count(*) from solidos_control.dirty_companies),
    'dirty_oldest_seconds',coalesce((select extract(epoch from(now()-min(first_dirty_at)))::bigint from solidos_control.dirty_companies),0),
    'assets',(select count(*) from commercial_intel.company_assets),
    'safe_assets',(select count(*) from commercial_intel.company_assets where commercial_status='COMMERCIAL_SAFE'),
    'review_assets',(select count(*) from commercial_intel.company_assets where commercial_status='REVIEW_REQUIRED'),
    'signals',(select count(*) from commercial_intel.business_signals where active),
    'exportable_memberships',(select count(*) from commercial_intel.product_memberships where exportable)
  ),
  'sources',jsonb_build_object(
    'enabled',(select count(*) from booked_solid.source_catalog where enabled),
    'healthy',(select count(*) from solidos_control.source_health where enabled and health_state='HEALTHY'),
    'degraded',(select count(*) from solidos_control.source_health where enabled and health_state='DEGRADED'),
    'cooling',(select count(*) from solidos_control.source_health where enabled and health_state='COOLING')
  ),
  'sheet_engine',jsonb_build_object(
    'pending_requests',(select count(*) from solidos_control.sheet_sync_requests where status='PENDING'),
    'blocked_not_configured',(select count(*) from solidos_control.sheet_sync_requests where status='BLOCKED_NOT_CONFIGURED'),
    'targets',(select count(*) from commercial_intel.sheet_targets where sync_enabled),
    'last_success',(select max(last_sync_at) from commercial_intel.sheet_targets where upper(coalesce(last_sync_status,''))='SUCCESS')
  ),
  'safety',jsonb_build_object(
    'email_enabled',(select email_enabled from booked_solid.runtime_settings where id=true),
    'sms_enabled',(select sms_enabled from booked_solid.runtime_settings where id=true),
    'buyer_outreach_enabled',(select buyer_outreach_enabled from commercial_intel.settings where id=true),
    'personal_pii_export',(select allow_personal_pii_export from commercial_intel.settings where id=true)
  )
);
$function$;
