create schema if not exists solidos_control;

create table if not exists solidos_control.settings (
  id boolean primary key default true check (id),
  system_name text not null default 'SolidOS',
  mode text not null default 'CANARY',
  planner_interval_minutes integer not null default 5 check (planner_interval_minutes between 1 and 60),
  planner_target_discoveries integer not null default 3 check (planner_target_discoveries between 1 and 20),
  planner_max_discoveries integer not null default 6 check (planner_max_discoveries between 1 and 50),
  due_backlog_soft_limit integer not null default 30 check (due_backlog_soft_limit >= 1),
  intel_dirty_batch_size integer not null default 50 check (intel_dirty_batch_size between 1 and 500),
  source_error_open_threshold integer not null default 4 check (source_error_open_threshold between 2 and 20),
  updated_at timestamptz not null default now()
);
insert into solidos_control.settings(id) values(true) on conflict(id) do nothing;

create table if not exists solidos_control.dirty_companies (
  company_id uuid primary key references booked_solid.companies(id) on delete cascade,
  reason text not null,
  priority numeric not null default 50,
  first_dirty_at timestamptz not null default now(),
  last_dirty_at timestamptz not null default now(),
  attempts integer not null default 0,
  last_error text,
  locked_at timestamptz,
  updated_at timestamptz not null default now()
);
create index if not exists dirty_companies_pick_idx
  on solidos_control.dirty_companies(priority desc,last_dirty_at,company_id);

create table if not exists solidos_control.health_events (
  id bigint generated by default as identity primary key,
  component text not null,
  severity text not null check (severity in ('INFO','WARN','ERROR')),
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists health_events_created_idx on solidos_control.health_events(created_at desc);

create or replace function solidos_control.mark_company_dirty(
  p_company_id uuid,p_reason text,p_priority numeric default 50
) returns void
language plpgsql
security invoker
set search_path=''
as $function$
begin
  if p_company_id is null then return; end if;
  insert into solidos_control.dirty_companies(company_id,reason,priority)
  values(p_company_id,coalesce(nullif(p_reason,''),'core_change'),coalesce(p_priority,50))
  on conflict(company_id) do update set
    reason=excluded.reason,
    priority=greatest(solidos_control.dirty_companies.priority,excluded.priority),
    last_dirty_at=now(),updated_at=now();
end
$function$;

create or replace function solidos_control.core_change_dirty_trigger()
returns trigger
language plpgsql
security invoker
set search_path=''
as $function$
declare v_company uuid;
begin
  if tg_table_name='companies' then v_company:=new.id; else v_company:=new.company_id; end if;
  perform solidos_control.mark_company_dirty(v_company,tg_table_name||':'||lower(tg_op),
    case when tg_table_name in ('leads','evidence') then 80 else 60 end);
  return new;
end
$function$;

drop trigger if exists solidos_dirty_companies on booked_solid.companies;
create trigger solidos_dirty_companies after insert or update on booked_solid.companies
for each row execute function solidos_control.core_change_dirty_trigger();

drop trigger if exists solidos_dirty_leads on booked_solid.leads;
create trigger solidos_dirty_leads after insert or update on booked_solid.leads
for each row execute function solidos_control.core_change_dirty_trigger();

drop trigger if exists solidos_dirty_evidence on booked_solid.evidence;
create trigger solidos_dirty_evidence after insert or update on booked_solid.evidence
for each row execute function solidos_control.core_change_dirty_trigger();

drop trigger if exists solidos_dirty_contacts on booked_solid.contacts;
create trigger solidos_dirty_contacts after insert or update on booked_solid.contacts
for each row execute function solidos_control.core_change_dirty_trigger();

create or replace function commercial_intel.refresh_company_asset_one(p_company_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $function$
declare v_count integer:=0;
begin
  with lead_best as (
    select distinct on (company_id)
      company_id,fit_score,opportunity_score,priority_band,offer,why_now,status
    from booked_solid.leads where company_id=p_company_id
    order by company_id,opportunity_score desc nulls last,updated_at desc
  ), contact_flags as (
    select company_id,
      bool_or(full_name is not null) has_named_people,
      bool_or(email is not null and full_name is not null) has_personal_email,
      bool_or(phone is not null and full_name is not null) has_personal_phone
    from booked_solid.contacts where company_id=p_company_id group by company_id
  )
  insert into commercial_intel.company_assets(
    company_id,company_name,canonical_domain,website_url,trade,location_text,state,country,
    core_status,source_first_seen,source_last_seen,rights_status,commercial_status,
    commercial_score,fit_score,opportunity_score,priority_band,recommended_offer,why_now,
    freshness_score,last_core_update,last_evaluated_at,has_named_people,has_personal_email,
    has_personal_phone,safe_company_payload,restriction_reasons,metadata,updated_at
  )
  select c.id,c.name,c.canonical_domain,c.website_url,c.trade,c.location_text,c.state,c.country,
    c.status,c.source_first_seen,c.source_last_seen,coalesce(sr.rights_status,'REVIEW_REQUIRED'),
    case when coalesce(sr.rights_status,'REVIEW_REQUIRED')='ALLOWED' then 'COMMERCIAL_SAFE'
         when coalesce(sr.rights_status,'REVIEW_REQUIRED')='BLOCKED' then 'BLOCKED_FROM_RESALE'
         when coalesce(sr.rights_status,'REVIEW_REQUIRED')='INTERNAL_ONLY' then 'INTERNAL_ONLY'
         else 'REVIEW_REQUIRED' end,
    least(100,greatest(0,coalesce(lb.opportunity_score,0)*0.55+
      coalesce(lb.fit_score,c.fit_score,0)*0.35+
      case when c.website_url is not null then 5 else 0 end+
      case when c.state is not null then 5 else 0 end)),
    coalesce(lb.fit_score,c.fit_score),lb.opportunity_score,lb.priority_band,
    coalesce(lb.offer,c.recommended_offer),lb.why_now,
    greatest(0,100-extract(epoch from(now()-coalesce(c.updated_at,c.created_at)))/86400.0*2),
    c.updated_at,now(),coalesce(cf.has_named_people,false),coalesce(cf.has_personal_email,false),
    coalesce(cf.has_personal_phone,false),
    jsonb_strip_nulls(jsonb_build_object(
      'company_name',c.name,'canonical_domain',c.canonical_domain,'website_url',c.website_url,
      'trade',c.trade,'location_text',c.location_text,'state',c.state,'country',c.country,
      'commercial_score',round((least(100,greatest(0,coalesce(lb.opportunity_score,0)*0.55+
        coalesce(lb.fit_score,c.fit_score,0)*0.35+
        case when c.website_url is not null then 5 else 0 end+
        case when c.state is not null then 5 else 0 end)))::numeric,2),
      'opportunity_score',lb.opportunity_score,'priority_band',lb.priority_band,
      'recommended_offer',coalesce(lb.offer,c.recommended_offer)
    )),
    case when coalesce(sr.rights_status,'REVIEW_REQUIRED')='ALLOWED' then '{}'::text[]
         when coalesce(sr.rights_status,'REVIEW_REQUIRED')='BLOCKED' then array['SOURCE_BLOCKED']::text[]
         when coalesce(sr.rights_status,'REVIEW_REQUIRED')='INTERNAL_ONLY' then array['SOURCE_INTERNAL_ONLY']::text[]
         else array['SOURCE_RIGHTS_REVIEW_REQUIRED']::text[] end,
    jsonb_build_object('core_lead_status',lb.status,'source_rights_id',sr.id,'core_enrichment_version',c.enrichment_version),
    now()
  from booked_solid.companies c
  left join lead_best lb on lb.company_id=c.id
  left join contact_flags cf on cf.company_id=c.id
  left join commercial_intel.source_rights sr on sr.source_slug=c.source_first_seen
  where c.id=p_company_id
  on conflict(company_id) do update set
    company_name=excluded.company_name,canonical_domain=excluded.canonical_domain,website_url=excluded.website_url,
    trade=excluded.trade,location_text=excluded.location_text,state=excluded.state,country=excluded.country,
    core_status=excluded.core_status,source_first_seen=excluded.source_first_seen,source_last_seen=excluded.source_last_seen,
    rights_status=excluded.rights_status,commercial_status=excluded.commercial_status,
    commercial_score=excluded.commercial_score,fit_score=excluded.fit_score,opportunity_score=excluded.opportunity_score,
    priority_band=excluded.priority_band,recommended_offer=excluded.recommended_offer,why_now=excluded.why_now,
    freshness_score=excluded.freshness_score,last_core_update=excluded.last_core_update,last_evaluated_at=excluded.last_evaluated_at,
    has_named_people=excluded.has_named_people,has_personal_email=excluded.has_personal_email,
    has_personal_phone=excluded.has_personal_phone,safe_company_payload=excluded.safe_company_payload,
    restriction_reasons=excluded.restriction_reasons,metadata=excluded.metadata,updated_at=now();
  get diagnostics v_count=row_count;
  return jsonb_build_object('company_id',p_company_id,'assets_upserted',v_count,'at',now());
end
$function$;

create or replace function commercial_intel.refresh_business_signals_one(p_company_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $function$
declare v_count integer:=0;
begin
  insert into commercial_intel.business_signals(
    company_id,signal_type,evidence_count,avg_confidence,first_observed_at,last_observed_at,
    source_domains,active,metadata,updated_at
  )
  select e.company_id,e.evidence_type,count(*)::int,avg(e.confidence),min(e.observed_at),max(e.observed_at),
    array_agg(distinct lower(split_part(regexp_replace(e.source_url,'^https?://','','i'),'/',1)))
      filter(where e.source_url is not null),
    true,jsonb_build_object('commercial_transform','aggregate_only','raw_snippets_exported',false),now()
  from booked_solid.evidence e
  where e.company_id=p_company_id
    and e.evidence_type in (
      'estimation_pain','scale_signal','buyer_signal','permit_activity','workflow_complexity',
      'property_operations','trigger_active_hiring','trade_license','intel_business_profile',
      'trigger_expansion','recurring_contracts','field_quoting','trigger_quote_speed',
      'trigger_multi_location_growth','change_orders','trigger_manual_workflow',
      'trigger_recurring_service','fit_signal','trigger_change_order_workflow',
      'trigger_hiring_estimator','association_membership'
    )
    and coalesce(e.metadata->>'active','true')<>'false'
  group by e.company_id,e.evidence_type
  on conflict(company_id,signal_type) do update set
    evidence_count=excluded.evidence_count,avg_confidence=excluded.avg_confidence,
    first_observed_at=excluded.first_observed_at,last_observed_at=excluded.last_observed_at,
    source_domains=excluded.source_domains,active=true,metadata=excluded.metadata,updated_at=now();
  get diagnostics v_count=row_count;
  update commercial_intel.business_signals bs set active=false,updated_at=now()
  where bs.company_id=p_company_id
    and not exists(select 1 from booked_solid.evidence e
      where e.company_id=p_company_id and e.evidence_type=bs.signal_type
        and coalesce(e.metadata->>'active','true')<>'false');
  return jsonb_build_object('company_id',p_company_id,'signals_upserted',v_count,'at',now());
end
$function$;

create or replace function commercial_intel.refresh_product_memberships_one(p_company_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $function$
declare v_count integer:=0;
begin
  with signal_rollup as (
    select company_id,array_agg(signal_type order by signal_type) filter(where active) signal_types,
      jsonb_object_agg(signal_type,evidence_count) filter(where active) signal_counts,
      array(select distinct d from commercial_intel.business_signals b2,
        unnest(coalesce(b2.source_domains,'{}'::text[])) d
        where b2.company_id=p_company_id and b2.active order by d) evidence_domains
    from commercial_intel.business_signals where company_id=p_company_id group by company_id
  ), x as (
    select p.id product_id,p.slug product_slug,a.*,
      coalesce(sr.signal_types,'{}'::text[]) signal_types,
      coalesce(sr.signal_counts,'{}'::jsonb) signal_counts,
      coalesce(sr.evidence_domains,'{}'::text[]) evidence_domains,
      case
        when p.slug='contractor-starter' then a.commercial_score>=55
        when p.slug='growth-signals' then coalesce(sr.signal_types,'{}'::text[]) &&
          array['scale_signal','trigger_expansion','trigger_multi_location_growth','trigger_active_hiring']
        when p.slug='automation-opportunities' then coalesce(sr.signal_types,'{}'::text[]) &&
          array['estimation_pain','workflow_complexity','trigger_manual_workflow','trigger_quote_speed','change_orders','field_quoting']
        when p.slug='agency-feed' then a.commercial_score>=50
        when p.slug='custom-icp' then true else false end eligible_calc
    from commercial_intel.products p
    join commercial_intel.company_assets a on a.company_id=p_company_id
    left join signal_rollup sr on sr.company_id=a.company_id
    where p.status='active'
  )
  insert into commercial_intel.product_memberships(
    product_id,company_id,eligible,exportable,product_score,match_reasons,export_payload,evaluated_at
  )
  select x.product_id,x.company_id,x.eligible_calc,
    x.eligible_calc and x.commercial_status='COMMERCIAL_SAFE',
    least(100,greatest(0,x.commercial_score+
      case when cardinality(x.signal_types)>=3 then 8 when cardinality(x.signal_types)>=1 then 4 else 0 end)),
    array_remove(array[
      case when x.commercial_status='COMMERCIAL_SAFE' then 'COMPLIANCE_SAFE' else 'COMPLIANCE_NOT_CLEARED' end,
      case when x.commercial_score>=70 then 'HIGH_COMMERCIAL_SCORE' end,
      case when cardinality(x.signal_types)>0 then 'BUSINESS_SIGNALS_PRESENT' end,
      case when x.priority_band in ('hot','high','Hot','High') then 'CORE_HIGH_PRIORITY' end
    ],null),
    x.safe_company_payload||jsonb_build_object(
      'signal_summary',case when cardinality(x.signal_types)>0
        then 'Observed business signals: '||array_to_string(x.signal_types,', ')
        else 'No approved business-level signal currently available' end,
      'business_signals',x.signal_counts,'evidence_domains',to_jsonb(x.evidence_domains),
      'commercial_status',x.commercial_status,'rights_status',x.rights_status,
      'freshness_score',round(x.freshness_score::numeric,2)),now()
  from x
  on conflict(product_id,company_id) do update set
    eligible=excluded.eligible,exportable=excluded.exportable,product_score=excluded.product_score,
    match_reasons=excluded.match_reasons,export_payload=excluded.export_payload,evaluated_at=now();
  get diagnostics v_count=row_count;
  return jsonb_build_object('company_id',p_company_id,'memberships_upserted',v_count,'at',now());
end
$function$;

create or replace function commercial_intel.refresh_company_incremental(p_company_id uuid)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $function$
declare a jsonb; s jsonb; p jsonb;
begin
  perform commercial_intel.ensure_source_rights_registry();
  a:=commercial_intel.refresh_company_asset_one(p_company_id);
  s:=commercial_intel.refresh_business_signals_one(p_company_id);
  p:=commercial_intel.refresh_product_memberships_one(p_company_id);
  return jsonb_build_object('company_id',p_company_id,'asset',a,'signals',s,'products',p,'at',now());
end
$function$;

create or replace function commercial_intel.process_dirty_companies(p_limit integer default 50)
returns jsonb
language plpgsql
security invoker
set search_path=''
as $function$
declare r record; v_ok integer:=0; v_failed integer:=0; v_limit integer;
begin
  v_limit:=least(greatest(coalesce(p_limit,50),1),500);
  for r in select company_id from solidos_control.dirty_companies
    order by priority desc,last_dirty_at,company_id for update skip locked limit v_limit
  loop
    begin
      update solidos_control.dirty_companies set locked_at=now(),attempts=attempts+1,updated_at=now()
      where company_id=r.company_id;
      perform commercial_intel.refresh_company_incremental(r.company_id);
      delete from solidos_control.dirty_companies where company_id=r.company_id;
      v_ok:=v_ok+1;
    exception when others then
      update solidos_control.dirty_companies set locked_at=null,last_error=left(sqlerrm,500),updated_at=now()
      where company_id=r.company_id;
      v_failed:=v_failed+1;
    end;
  end loop;
  return jsonb_build_object('processed',v_ok,'failed',v_failed,
    'remaining',(select count(*) from solidos_control.dirty_companies),'at',now());
end
$function$;

create or replace function solidos_control.system_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path=''
as $function$
select jsonb_build_object(
  'system','SolidOS','snapshot_at',now(),'mode',(select mode from solidos_control.settings where id=true),
  'core',jsonb_build_object(
    'companies',(select count(*) from booked_solid.companies),
    'leads',(select count(*) from booked_solid.leads),
    'qualified',(select count(*) from booked_solid.leads where lower(status)='qualified'),
    'candidates',(select count(*) from booked_solid.leads where lower(status)='candidate'),
    'due_now',(select count(*) from booked_solid.work_queue where status='pending' and available_at<=now()),
    'scheduled_future',(select count(*) from booked_solid.work_queue where status='pending' and available_at>now()),
    'running',(select count(*) from booked_solid.work_queue where status='running'),
    'failed_terminal',(select count(*) from booked_solid.work_queue where status='failed')),
  'intel',jsonb_build_object(
    'dirty_backlog',(select count(*) from solidos_control.dirty_companies),
    'dirty_oldest_seconds',coalesce((select extract(epoch from(now()-min(first_dirty_at)))::bigint from solidos_control.dirty_companies),0),
    'assets',(select count(*) from commercial_intel.company_assets),
    'safe_assets',(select count(*) from commercial_intel.company_assets where commercial_status='COMMERCIAL_SAFE'),
    'review_assets',(select count(*) from commercial_intel.company_assets where commercial_status='REVIEW_REQUIRED'),
    'signals',(select count(*) from commercial_intel.business_signals where active),
    'exportable_memberships',(select count(*) from commercial_intel.product_memberships where exportable)),
  'sources',jsonb_build_object(
    'enabled',(select count(*) from booked_solid.source_catalog where enabled),
    'degraded',(select count(*) from booked_solid.source_catalog where enabled and
      (consecutive_errors>=4 or coalesce(metadata->>'state','')='degraded')),
    'cooling',(select count(*) from booked_solid.source_catalog where enabled
      and nullif(metadata->>'cooldown_until','') is not null
      and (metadata->>'cooldown_until')::timestamptz>now())),
  'sheets',jsonb_build_object(
    'targets',(select count(*) from commercial_intel.sheet_targets where sync_enabled),
    'failed_targets',(select count(*) from commercial_intel.sheet_targets where sync_enabled
      and upper(coalesce(last_sync_status,''))='FAILED'),
    'last_success',(select max(last_sync_at) from commercial_intel.sheet_targets
      where upper(coalesce(last_sync_status,''))='SUCCESS')),
  'safety',jsonb_build_object(
    'email_enabled',(select email_enabled from booked_solid.runtime_settings where id=true),
    'sms_enabled',(select sms_enabled from booked_solid.runtime_settings where id=true),
    'buyer_outreach_enabled',(select buyer_outreach_enabled from commercial_intel.settings where id=true),
    'personal_pii_export',(select allow_personal_pii_export from commercial_intel.settings where id=true))
);
$function$;

do $$
begin
  if exists(select 1 from cron.job where jobname='commercial-intel-dirty-1m') then
    perform cron.unschedule((select jobid from cron.job where jobname='commercial-intel-dirty-1m'));
  end if;
  perform cron.schedule('commercial-intel-dirty-1m','* * * * *',
    'select commercial_intel.process_dirty_companies(50);');
end $$;
